name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore
        run: dotnet restore tests/TaskTracker.V1.Tests/TaskTracker.V1.Tests.csproj

      - name: Build (Debug)
        run: dotnet build -c Debug tests/TaskTracker.V1.Tests/TaskTracker.V1.Tests.csproj

      - name: Install Playwright CLI
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install Playwright browsers (Linux)
        run: playwright install --with-deps -p tests/TaskTracker.V1.Tests/TaskTracker.V1.Tests.csproj

      - name: Test
        run: dotnet test -c Debug --no-build tests/TaskTracker.V1.Tests/TaskTracker.V1.Tests.csproj --logger "trx;LogFileName=test-results.trx"
